// Wallpaper picker palette + power menu. Generated by theme-switch (matugen) -- do not edit by hand.
.pragma library
var COLORS = {
    bg: "#1a1110",
    fg: "#f1dfdb",
    accent: "#ffb4a8",
    secondary: "#e7bdb6",
    surface_variant: "#534341",
    muted: "#a08c89",
}
