// Wallpaper picker palette + power menu. Generated by theme-switch (matugen) -- do not edit by hand.
.pragma library
var COLORS = {
    bg: "#f7f9ff",
    fg: "#181c20",
    accent: "#2e628c",
    secondary: "#51606f",
    surface_variant: "#42474e",
    muted: "#72777f",
}
