// Wallpaper picker palette + power menu. Generated by theme-switch (matugen) -- do not edit by hand.
.pragma library
var COLORS = {
    bg: "#0e1415",
    fg: "#dee4e4",
    accent: "#81d4dc",
    secondary: "#b1cbce",
    surface_variant: "#3f4849",
    muted: "#899393",
}
