// Wallpaper picker palette + power menu. Generated by theme-switch (matugen) -- do not edit by hand.
.pragma library
var COLORS = {
    bg: "#0e1415",
    fg: "#dee3e5",
    accent: "#82d3e0",
    secondary: "#b1cbd0",
    surface_variant: "#3f484a",
    muted: "#899294",
}
