// Generated by wall-pick -- do not edit by hand
.pragma library
var ACTIVE = "/home/oryza/.config/sway/walls/fox/two.jpg";
var THEME_SWITCH = "/home/oryza/.config/sway/scripts/theme-switch";
var WALLS = [
  {
    "name": "blurry_cutie.jpg",
    "path": "/home/oryza/.config/sway/walls/fox/blurry_cutie.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/blurry_cutie.jpg",
    "dir": "fox",
    "rel": "fox/blurry_cutie.jpg"
  },
  {
    "name": "confused.jpg",
    "path": "/home/oryza/.config/sway/walls/fox/confused.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/confused.jpg",
    "dir": "fox",
    "rel": "fox/confused.jpg"
  },
  {
    "name": "indawater.jpg",
    "path": "/home/oryza/.config/sway/walls/fox/indawater.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/indawater.jpg",
    "dir": "fox",
    "rel": "fox/indawater.jpg"
  },
  {
    "name": "jumping.jpg",
    "path": "/home/oryza/.config/sway/walls/fox/jumping.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/jumping.jpg",
    "dir": "fox",
    "rel": "fox/jumping.jpg"
  },
  {
    "name": "main.jpg",
    "path": "/home/oryza/.config/sway/walls/fox/main.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/main.jpg",
    "dir": "fox",
    "rel": "fox/main.jpg"
  },
  {
    "name": "pexels-vishpix-37321967.jpg",
    "path": "/home/oryza/.config/sway/walls/fox/pexels-vishpix-37321967.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/pexels-vishpix-37321967.jpg",
    "dir": "fox",
    "rel": "fox/pexels-vishpix-37321967.jpg"
  },
  {
    "name": "resting.jpg",
    "path": "/home/oryza/.config/sway/walls/fox/resting.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/resting.jpg",
    "dir": "fox",
    "rel": "fox/resting.jpg"
  },
  {
    "name": "two.jpg",
    "path": "/home/oryza/.config/sway/walls/fox/two.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/two.jpg",
    "dir": "fox",
    "rel": "fox/two.jpg"
  },
  {
    "name": "wallhaven-0q6dxl_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-0q6dxl_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-0q6dxl_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-0q6dxl_1920x1080.png"
  },
  {
    "name": "wallhaven-0qkwe7_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-0qkwe7_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-0qkwe7_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-0qkwe7_1920x1080.png"
  },
  {
    "name": "wallhaven-42jkk9_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-42jkk9_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-42jkk9_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-42jkk9_1920x1080.png"
  },
  {
    "name": "wallhaven-4gq1gd_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-4gq1gd_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-4gq1gd_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-4gq1gd_1920x1080.png"
  },
  {
    "name": "wallhaven-4gy3p7_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-4gy3p7_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-4gy3p7_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-4gy3p7_1920x1080.png"
  },
  {
    "name": "wallhaven-4odmzl_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-4odmzl_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-4odmzl_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-4odmzl_1920x1080.png"
  },
  {
    "name": "wallhaven-6k7d1q.jpg",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-6k7d1q.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-6k7d1q.jpg",
    "dir": "fox",
    "rel": "fox/wallhaven-6k7d1q.jpg"
  },
  {
    "name": "wallhaven-73k29y.jpg",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-73k29y.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-73k29y.jpg",
    "dir": "fox",
    "rel": "fox/wallhaven-73k29y.jpg"
  },
  {
    "name": "wallhaven-d5ylgm_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-d5ylgm_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-d5ylgm_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-d5ylgm_1920x1080.png"
  },
  {
    "name": "wallhaven-j5x9jp_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-j5x9jp_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-j5x9jp_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-j5x9jp_1920x1080.png"
  },
  {
    "name": "wallhaven-mpwed8_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-mpwed8_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-mpwed8_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-mpwed8_1920x1080.png"
  },
  {
    "name": "wallhaven-nrpz8q_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-nrpz8q_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-nrpz8q_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-nrpz8q_1920x1080.png"
  },
  {
    "name": "wallhaven-p8pkw3_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-p8pkw3_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-p8pkw3_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-p8pkw3_1920x1080.png"
  },
  {
    "name": "wallhaven-p8y57m_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-p8y57m_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-p8y57m_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-p8y57m_1920x1080.png"
  },
  {
    "name": "wallhaven-q655dl_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-q655dl_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-q655dl_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-q655dl_1920x1080.png"
  },
  {
    "name": "wallhaven-w87mvr_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-w87mvr_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-w87mvr_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-w87mvr_1920x1080.png"
  },
  {
    "name": "wallhaven-zx7m7w_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/fox/wallhaven-zx7m7w_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-zx7m7w_1920x1080.png",
    "dir": "fox",
    "rel": "fox/wallhaven-zx7m7w_1920x1080.png"
  },
  {
    "name": "wallhaven-4216om_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-4216om_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-4216om_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-4216om_1920x1080.png"
  },
  {
    "name": "wallhaven-43q76d_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-43q76d_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-43q76d_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-43q76d_1920x1080.png"
  },
  {
    "name": "wallhaven-47okj9_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-47okj9_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-47okj9_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-47okj9_1920x1080.png"
  },
  {
    "name": "wallhaven-4811lk_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-4811lk_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-4811lk_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-4811lk_1920x1080.png"
  },
  {
    "name": "wallhaven-49ml11_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-49ml11_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-49ml11_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-49ml11_1920x1080.png"
  },
  {
    "name": "wallhaven-49we3w_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-49we3w_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-49we3w_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-49we3w_1920x1080.png"
  },
  {
    "name": "wallhaven-4ym6jg_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-4ym6jg_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-4ym6jg_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-4ym6jg_1920x1080.png"
  },
  {
    "name": "wallhaven-6d17mw_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-6d17mw_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-6d17mw_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-6d17mw_1920x1080.png"
  },
  {
    "name": "wallhaven-85eqe2_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-85eqe2_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-85eqe2_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-85eqe2_1920x1080.png"
  },
  {
    "name": "wallhaven-8grwly_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-8grwly_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-8grwly_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-8grwly_1920x1080.png"
  },
  {
    "name": "wallhaven-96j86d_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-96j86d_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-96j86d_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-96j86d_1920x1080.png"
  },
  {
    "name": "wallhaven-d6z28l_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-d6z28l_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-d6z28l_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-d6z28l_1920x1080.png"
  },
  {
    "name": "wallhaven-e89vvw_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-e89vvw_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-e89vvw_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-e89vvw_1920x1080.png"
  },
  {
    "name": "wallhaven-gwp2w3_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-gwp2w3_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-gwp2w3_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-gwp2w3_1920x1080.png"
  },
  {
    "name": "wallhaven-kw2q2d_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-kw2q2d_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-kw2q2d_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-kw2q2d_1920x1080.png"
  },
  {
    "name": "wallhaven-kxopp7_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-kxopp7_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-kxopp7_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-kxopp7_1920x1080.png"
  },
  {
    "name": "wallhaven-mprjg1_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-mprjg1_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-mprjg1_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-mprjg1_1920x1080.png"
  },
  {
    "name": "wallhaven-neygol_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-neygol_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-neygol_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-neygol_1920x1080.png"
  },
  {
    "name": "wallhaven-nkj5q4_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-nkj5q4_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-nkj5q4_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-nkj5q4_1920x1080.png"
  },
  {
    "name": "wallhaven-nz8ewj_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-nz8ewj_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-nz8ewj_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-nz8ewj_1920x1080.png"
  },
  {
    "name": "wallhaven-wqm2e6_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-wqm2e6_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-wqm2e6_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-wqm2e6_1920x1080.png"
  },
  {
    "name": "wallhaven-yjwd6g_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-yjwd6g_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-yjwd6g_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-yjwd6g_1920x1080.png"
  },
  {
    "name": "wallhaven-z8dvvj_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-z8dvvj_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-z8dvvj_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-z8dvvj_1920x1080.png"
  },
  {
    "name": "wallhaven-zyzwqg_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/lain/wallhaven-zyzwqg_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-zyzwqg_1920x1080.png",
    "dir": "lain",
    "rel": "lain/wallhaven-zyzwqg_1920x1080.png"
  },
  {
    "name": "521058ldsdl.jpg",
    "path": "/home/oryza/.config/sway/walls/paintings/521058ldsdl.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/521058ldsdl.jpg",
    "dir": "paintings",
    "rel": "paintings/521058ldsdl.jpg"
  },
  {
    "name": "532031ldsdl.jpg",
    "path": "/home/oryza/.config/sway/walls/paintings/532031ldsdl.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/532031ldsdl.jpg",
    "dir": "paintings",
    "rel": "paintings/532031ldsdl.jpg"
  },
  {
    "name": "533369ldsdl.jpg",
    "path": "/home/oryza/.config/sway/walls/paintings/533369ldsdl.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/533369ldsdl.jpg",
    "dir": "paintings",
    "rel": "paintings/533369ldsdl.jpg"
  },
  {
    "name": "553609ldsdl.jpg",
    "path": "/home/oryza/.config/sway/walls/paintings/553609ldsdl.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/553609ldsdl.jpg",
    "dir": "paintings",
    "rel": "paintings/553609ldsdl.jpg"
  },
  {
    "name": "557913ldsdl.jpg",
    "path": "/home/oryza/.config/sway/walls/paintings/557913ldsdl.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/557913ldsdl.jpg",
    "dir": "paintings",
    "rel": "paintings/557913ldsdl.jpg"
  },
  {
    "name": "8tk8o5nipr451.jpg",
    "path": "/home/oryza/.config/sway/walls/paintings/8tk8o5nipr451.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/8tk8o5nipr451.jpg",
    "dir": "paintings",
    "rel": "paintings/8tk8o5nipr451.jpg"
  },
  {
    "name": "912905absdl.jpg",
    "path": "/home/oryza/.config/sway/walls/paintings/912905absdl.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/912905absdl.jpg",
    "dir": "paintings",
    "rel": "paintings/912905absdl.jpg"
  },
  {
    "name": "wallhaven-1qp2mw_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/paintings/wallhaven-1qp2mw_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-1qp2mw_1920x1080.png",
    "dir": "paintings",
    "rel": "paintings/wallhaven-1qp2mw_1920x1080.png"
  },
  {
    "name": "wallhaven-213mrg_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/paintings/wallhaven-213mrg_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-213mrg_1920x1080.png",
    "dir": "paintings",
    "rel": "paintings/wallhaven-213mrg_1920x1080.png"
  },
  {
    "name": "wallhaven-d8w8y3_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/paintings/wallhaven-d8w8y3_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-d8w8y3_1920x1080.png",
    "dir": "paintings",
    "rel": "paintings/wallhaven-d8w8y3_1920x1080.png"
  },
  {
    "name": "wallhaven-e8w77r_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/paintings/wallhaven-e8w77r_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-e8w77r_1920x1080.png",
    "dir": "paintings",
    "rel": "paintings/wallhaven-e8w77r_1920x1080.png"
  },
  {
    "name": "wallhaven-lyjywy_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/paintings/wallhaven-lyjywy_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-lyjywy_1920x1080.png",
    "dir": "paintings",
    "rel": "paintings/wallhaven-lyjywy_1920x1080.png"
  },
  {
    "name": "wallhaven-rrerk1_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/paintings/wallhaven-rrerk1_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-rrerk1_1920x1080.png",
    "dir": "paintings",
    "rel": "paintings/wallhaven-rrerk1_1920x1080.png"
  },
  {
    "name": "valley-dawn.jpg",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/valley-dawn.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/valley-dawn.jpg",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/valley-dawn.jpg"
  },
  {
    "name": "wallhaven-1kzdg1_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-1kzdg1_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-1kzdg1_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-1kzdg1_1920x1080.png"
  },
  {
    "name": "wallhaven-21ejd9_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-21ejd9_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-21ejd9_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-21ejd9_1920x1080.png"
  },
  {
    "name": "wallhaven-2y2ymx_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-2y2ymx_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-2y2ymx_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-2y2ymx_1920x1080.png"
  },
  {
    "name": "wallhaven-3qlxjy_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-3qlxjy_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-3qlxjy_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-3qlxjy_1920x1080.png"
  },
  {
    "name": "wallhaven-72k9o3_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-72k9o3_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-72k9o3_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-72k9o3_1920x1080.png"
  },
  {
    "name": "wallhaven-9d36rw_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-9d36rw_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-9d36rw_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-9d36rw_1920x1080.png"
  },
  {
    "name": "wallhaven-9mo7kw_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-9mo7kw_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-9mo7kw_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-9mo7kw_1920x1080.png"
  },
  {
    "name": "wallhaven-9mv6ew_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-9mv6ew_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-9mv6ew_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-9mv6ew_1920x1080.png"
  },
  {
    "name": "wallhaven-9o2mwd_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-9o2mwd_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-9o2mwd_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-9o2mwd_1920x1080.png"
  },
  {
    "name": "wallhaven-9o2o81_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-9o2o81_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-9o2o81_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-9o2o81_1920x1080.png"
  },
  {
    "name": "wallhaven-d6mg33_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-d6mg33_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-d6mg33_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-d6mg33_1920x1080.png"
  },
  {
    "name": "wallhaven-e89l8k_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-e89l8k_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-e89l8k_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-e89l8k_1920x1080.png"
  },
  {
    "name": "wallhaven-gw7kr7_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-gw7kr7_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-gw7kr7_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-gw7kr7_1920x1080.png"
  },
  {
    "name": "wallhaven-j3328w_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-j3328w_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-j3328w_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-j3328w_1920x1080.png"
  },
  {
    "name": "wallhaven-je5wl5_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-je5wl5_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-je5wl5_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-je5wl5_1920x1080.png"
  },
  {
    "name": "wallhaven-k87kj6_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-k87kj6_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-k87kj6_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-k87kj6_1920x1080.png"
  },
  {
    "name": "wallhaven-l315vy_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-l315vy_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-l315vy_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-l315vy_1920x1080.png"
  },
  {
    "name": "wallhaven-ly897r_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-ly897r_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-ly897r_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-ly897r_1920x1080.png"
  },
  {
    "name": "wallhaven-ml1ey9_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-ml1ey9_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-ml1ey9_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-ml1ey9_1920x1080.png"
  },
  {
    "name": "wallhaven-ml9g38_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-ml9g38_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-ml9g38_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-ml9g38_1920x1080.png"
  },
  {
    "name": "wallhaven-og23ep_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-og23ep_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-og23ep_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-og23ep_1920x1080.png"
  },
  {
    "name": "wallhaven-og33pm_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-og33pm_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-og33pm_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-og33pm_1920x1080.png"
  },
  {
    "name": "wallhaven-ogg3zp_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-ogg3zp_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-ogg3zp_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-ogg3zp_1920x1080.png"
  },
  {
    "name": "wallhaven-pok5v9_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-pok5v9_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-pok5v9_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-pok5v9_1920x1080.png"
  },
  {
    "name": "wallhaven-qrg8kq_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-qrg8kq_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-qrg8kq_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-qrg8kq_1920x1080.png"
  },
  {
    "name": "wallhaven-qrmkqq_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-qrmkqq_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-qrmkqq_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-qrmkqq_1920x1080.png"
  },
  {
    "name": "wallhaven-rd83mq_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-rd83mq_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-rd83mq_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-rd83mq_1920x1080.png"
  },
  {
    "name": "wallhaven-vpgqrm_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-vpgqrm_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-vpgqrm_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-vpgqrm_1920x1080.png"
  },
  {
    "name": "wallhaven-vpp86l_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-vpp86l_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-vpp86l_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-vpp86l_1920x1080.png"
  },
  {
    "name": "wallhaven-x6225z_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-x6225z_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-x6225z_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-x6225z_1920x1080.png"
  },
  {
    "name": "wallhaven-xedg6l_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-xedg6l_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-xedg6l_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-xedg6l_1920x1080.png"
  },
  {
    "name": "wallhaven-xedleo_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-xedleo_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-xedleo_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-xedleo_1920x1080.png"
  },
  {
    "name": "wallhaven-zp5z2w_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/skies-n-clouds/wallhaven-zp5z2w_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-zp5z2w_1920x1080.png",
    "dir": "skies-n-clouds",
    "rel": "skies-n-clouds/wallhaven-zp5z2w_1920x1080.png"
  },
  {
    "name": "ghibli-valley.png",
    "path": "/home/oryza/.config/sway/walls/ghibli/ghibli-valley.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/ghibli-valley.png",
    "dir": "ghibli",
    "rel": "ghibli/ghibli-valley.png"
  },
  {
    "name": "wallhaven-48p6j0_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/ghibli/wallhaven-48p6j0_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-48p6j0_1920x1080.png",
    "dir": "ghibli",
    "rel": "ghibli/wallhaven-48p6j0_1920x1080.png"
  },
  {
    "name": "wallhaven-6q8m3w_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/ghibli/wallhaven-6q8m3w_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-6q8m3w_1920x1080.png",
    "dir": "ghibli",
    "rel": "ghibli/wallhaven-6q8m3w_1920x1080.png"
  },
  {
    "name": "wallhaven-nz3r9w_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/ghibli/wallhaven-nz3r9w_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-nz3r9w_1920x1080.png",
    "dir": "ghibli",
    "rel": "ghibli/wallhaven-nz3r9w_1920x1080.png"
  },
  {
    "name": "wallhaven-yx5kml_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/ghibli/wallhaven-yx5kml_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-yx5kml_1920x1080.png",
    "dir": "ghibli",
    "rel": "ghibli/wallhaven-yx5kml_1920x1080.png"
  },
  {
    "name": "the-last-tour-i-wanted-a-background-for-my-pc-so-i-modified-v0-zxtzwqhswncc1.webp",
    "path": "/home/oryza/.config/sway/walls/idk-which-anime/the-last-tour-i-wanted-a-background-for-my-pc-so-i-modified-v0-zxtzwqhswncc1.webp",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/the-last-tour-i-wanted-a-background-for-my-pc-so-i-modified-v0-zxtzwqhswncc1.webp",
    "dir": "idk-which-anime",
    "rel": "idk-which-anime/the-last-tour-i-wanted-a-background-for-my-pc-so-i-modified-v0-zxtzwqhswncc1.webp"
  },
  {
    "name": "sand-dune.jpg",
    "path": "/home/oryza/.config/sway/walls/non-category/sand-dune.jpg",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/sand-dune.jpg",
    "dir": "non-category",
    "rel": "non-category/sand-dune.jpg"
  },
  {
    "name": "space-station.png",
    "path": "/home/oryza/.config/sway/walls/non-category/space-station.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/space-station.png",
    "dir": "non-category",
    "rel": "non-category/space-station.png"
  },
  {
    "name": "wallhaven-13oqeg_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-13oqeg_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-13oqeg_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-13oqeg_1920x1080.png"
  },
  {
    "name": "wallhaven-21ow86_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-21ow86_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-21ow86_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-21ow86_1920x1080.png"
  },
  {
    "name": "wallhaven-3q66wd_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-3q66wd_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-3q66wd_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-3q66wd_1920x1080.png"
  },
  {
    "name": "wallhaven-5dpdz3_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-5dpdz3_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-5dpdz3_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-5dpdz3_1920x1080.png"
  },
  {
    "name": "wallhaven-6d8wgq_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-6d8wgq_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-6d8wgq_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-6d8wgq_1920x1080.png"
  },
  {
    "name": "wallhaven-9omq61_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-9omq61_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-9omq61_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-9omq61_1920x1080.png"
  },
  {
    "name": "wallhaven-e8883w_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-e8883w_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-e8883w_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-e8883w_1920x1080.png"
  },
  {
    "name": "wallhaven-jevokm_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-jevokm_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-jevokm_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-jevokm_1920x1080.png"
  },
  {
    "name": "wallhaven-lyyqr2_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-lyyqr2_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-lyyqr2_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-lyyqr2_1920x1080.png"
  },
  {
    "name": "wallhaven-lyyyv2_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-lyyyv2_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-lyyyv2_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-lyyyv2_1920x1080.png"
  },
  {
    "name": "wallhaven-mlz139_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-mlz139_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-mlz139_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-mlz139_1920x1080.png"
  },
  {
    "name": "wallhaven-o58dm5_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-o58dm5_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-o58dm5_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-o58dm5_1920x1080.png"
  },
  {
    "name": "wallhaven-og3d6l_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-og3d6l_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-og3d6l_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-og3d6l_1920x1080.png"
  },
  {
    "name": "wallhaven-po7l8j_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-po7l8j_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-po7l8j_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-po7l8j_1920x1080.png"
  },
  {
    "name": "wallhaven-qrjd7l_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-qrjd7l_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-qrjd7l_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-qrjd7l_1920x1080.png"
  },
  {
    "name": "wallhaven-rqjrzq_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-rqjrzq_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-rqjrzq_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-rqjrzq_1920x1080.png"
  },
  {
    "name": "wallhaven-x63gdd_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-x63gdd_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-x63gdd_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-x63gdd_1920x1080.png"
  },
  {
    "name": "wallhaven-xe6qdv_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-xe6qdv_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-xe6qdv_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-xe6qdv_1920x1080.png"
  },
  {
    "name": "wallhaven-yq2xol_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-yq2xol_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-yq2xol_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-yq2xol_1920x1080.png"
  },
  {
    "name": "wallhaven-yq5dmg_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-yq5dmg_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-yq5dmg_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-yq5dmg_1920x1080.png"
  },
  {
    "name": "wallhaven-yq7k9l_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-yq7k9l_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-yq7k9l_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-yq7k9l_1920x1080.png"
  },
  {
    "name": "wallhaven-yqxzqx_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/non-category/wallhaven-yqxzqx_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-yqxzqx_1920x1080.png",
    "dir": "non-category",
    "rel": "non-category/wallhaven-yqxzqx_1920x1080.png"
  },
  {
    "name": "main.png",
    "path": "/home/oryza/.config/sway/walls/eva/main.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/main.png",
    "dir": "eva",
    "rel": "eva/main.png"
  },
  {
    "name": "rei.png",
    "path": "/home/oryza/.config/sway/walls/eva/rei.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/rei.png",
    "dir": "eva",
    "rel": "eva/rei.png"
  },
  {
    "name": "wallhaven-28r1jm_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/eva/wallhaven-28r1jm_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-28r1jm_1920x1080.png",
    "dir": "eva",
    "rel": "eva/wallhaven-28r1jm_1920x1080.png"
  },
  {
    "name": "wallhaven-399ood_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/eva/wallhaven-399ood_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-399ood_1920x1080.png",
    "dir": "eva",
    "rel": "eva/wallhaven-399ood_1920x1080.png"
  },
  {
    "name": "wallhaven-39zpl3_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/eva/wallhaven-39zpl3_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-39zpl3_1920x1080.png",
    "dir": "eva",
    "rel": "eva/wallhaven-39zpl3_1920x1080.png"
  },
  {
    "name": "wallhaven-6opprx_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/eva/wallhaven-6opprx_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-6opprx_1920x1080.png",
    "dir": "eva",
    "rel": "eva/wallhaven-6opprx_1920x1080.png"
  },
  {
    "name": "wallhaven-j5k3op_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/eva/wallhaven-j5k3op_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-j5k3op_1920x1080.png",
    "dir": "eva",
    "rel": "eva/wallhaven-j5k3op_1920x1080.png"
  },
  {
    "name": "wallhaven-k91x7q_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/eva/wallhaven-k91x7q_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-k91x7q_1920x1080.png",
    "dir": "eva",
    "rel": "eva/wallhaven-k91x7q_1920x1080.png"
  },
  {
    "name": "wallhaven-m933gy_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/eva/wallhaven-m933gy_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-m933gy_1920x1080.png",
    "dir": "eva",
    "rel": "eva/wallhaven-m933gy_1920x1080.png"
  },
  {
    "name": "wallhaven-o5d6w5_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/eva/wallhaven-o5d6w5_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-o5d6w5_1920x1080.png",
    "dir": "eva",
    "rel": "eva/wallhaven-o5d6w5_1920x1080.png"
  },
  {
    "name": "wallhaven-rd8gew_1920x1080.png",
    "path": "/home/oryza/.config/sway/walls/eva/wallhaven-rd8gew_1920x1080.png",
    "thumb": "/home/oryza/.cache/wall-pick-thumbs/wallhaven-rd8gew_1920x1080.png",
    "dir": "eva",
    "rel": "eva/wallhaven-rd8gew_1920x1080.png"
  }
]
// Shared search matcher, used by both the QuickMenu wallpaper page and the
// standalone picker. Matches a wallpaper against a query by file name, the
// folder it lives in (dir) or its path relative to the walls root (rel), so
// e.g. all walls/fox/*.jpg match a search for "fox".
function matchesQuery(wall, query) {
    if (!query) return true
    var q = query.toLowerCase()
    if ((wall.name || "").toLowerCase().indexOf(q) >= 0) return true
    if ((wall.dir || "").toLowerCase().indexOf(q) >= 0) return true
    if ((wall.rel || "").toLowerCase().indexOf(q) >= 0) return true
    return false
}
