.pragma library
var SETTINGS = {
    borderWidth: 4,
    cornerRadius: 4,
    innerRadius: 6,
    barSide: "top",
    fontFamily: "GeistMono NFM",
    barBorder: false,
    barShadow: true,
    quickMenuBorder: true,
    quickMenuShadow: false,
    osdBorder: true,
    osdShadow: true,
    notificationBorder: true,
    notificationShadow: true,
    notificationCornerRadius: 4,
    barFullWidth: true,
    activeBar: "fox",
    nightLight: true,
    nightLightIntensity: 2,
    noiseLevel: 0,
    caffeine: true,
    barBorderWidth: 4,
    barCornerRadius: 0,
    barInnerRadius: 0,
    quickMenuBorderWidth: 4,
    quickMenuCornerRadius: 4,
    quickMenuInnerRadius: 4,
    osdPosition: "top-right",
    osdCornerRadius: 4,
    osdMargin: 8,
    foxStatusBar: true,
}
